baseurl: "/mssql-jobs-hadr"
logo: /media/madeira_icon.png
social-network-links:
  rss: false
  email: "eitan@madeiradata.com"
  google-plus: +EitanBlumin
  linkedin: eitanblumin
  github: EitanBlumin
  twitter: EitanBlumin
share-links-active:
  twitter: true
  facebook: true
  google: true
  linkedin: true
navbar-links:
  Availability Groups: "availability-groups"
  Database Mirroring: "database-mirroring"
  Classic Version: "classic"
  Madeira Data Solutions: "https://www.madeiradata.com"
theme: jekyll-theme-minimal
