baseurl: "/mssql-jobs-hadr"
logo: /media/madeira_icon.png
social-network-links:
  rss: false
  email: "info@madeiradata.com"
  linkedin: madeira-sql-server-services
  github: MadeiraData
  twitter: Madeira_Data
share-links-active:
  twitter: true
  facebook: true
  linkedin: true
nav:
  alwayson: "/availability-groups"
  mirroring: "/database-mirroring"
  classic: "/classic"
theme: jekyll-theme-minimal
show_downloads: true
