
logo: media/madeira_icon.png
social-network-links:
  rss: false
  email: "eitan@madeiradata.com"
  google-plus: +EitanBlumin
  linkedin: eitanblumin
  github: EitanBlumin
  twitter: EitanBlumin
share-links-active:
  twitter: true
  facebook: true
  google: true
  linkedin: true
theme: jekyll-theme-minimal
