baseurl: "/mssql-jobs-hadr"
logo: /media/madeira_icon.png
social-network-links:
  rss: false
  email: "eitan@madeiradata.com"
  google-plus: +EitanBlumin
  linkedin: eitanblumin
  github: EitanBlumin
  twitter: EitanBlumin
share-links-active:
  twitter: true
  facebook: true
  google: true
  linkedin: true
nav:
  alwayson: "availability-groups"
  mirroring: "database-mirroring"
  classic: "classic"
theme: jekyll-theme-leap-day
show_downloads: true
